services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: auto-backup
    container_name: auto-backup-app
    networks:
      - laravel_network
    ports:
      - "8888:8000"
    entrypoint: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./backup:/var/www/backup
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: auto-backup-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3310:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local